### PR TITLE
I18N : Add french translation on StatConfig.py

### LINKED ISSUE #37: French language translations of title template, headings, labels, etc
**Summary**
Add French translations of title template, headings, labels, etc for locale code fr.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

### PR DESCRIPTION
**Pull request by thomasbnt**
## Summary

Add **french language** in the `StatConfig.py` and **better indent the code**. 
## Closing Issues
Fixes #37

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Improvements to existing code, such as refactoring or optimizations (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](https://github.com/cicirello/.github/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by cicirello — APPROVED** [review]

**Comment by cicirello** [comment]
Hi @thomasbnt . Thanks for the contribution.  The spacing adjustments you made also make it cleaner for other contributors too.

**Comment by thomasbnt** [comment]
Good and sorry for this two mistakes.

**Comment by cicirello** [comment]
@thomasbnt no problem.

**Comment by cicirello** [comment]
@thomasbnt This just went live with release v1.9.0. :rocket:

**Comment by thomasbnt** [comment]
Youhouuu 🚀🚀🚀

**Pull request merged**
