### PR TITLE
i18n: add polish translation

### PR DESCRIPTION
**Pull request by YasiOnFire**
## Summary
I'm a native polish speaker. I've added polish translation that matches the context.

## Closing Issues
Closec #74

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvements to existing code, such as refactoring or optimizations (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](https://github.com/cicirello/.github/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cicirello** [comment]
@YasiOnFire Thank you for your interest in this. Someone else had already expressed interest in completing the Polish translation, and had already been assigned to the issue before your PR came in.

**Comment by YasiOnFire** [comment]
Yea I see they just copied my code.  :) Nice

**Comment by cicirello** [comment]
@YasiOnFire Are you sure? I'll investigate either way.

**Comment by YasiOnFire** [comment]
100%. There is no apostrophe in general polish use, and i used it in `{0}'s GitHub Activity` -> `Aktywność {0} na GitHub'ie` as a mistake. Also some verbs are not translatable in polish and I've used the terms we use in our company daily, and they fit best.

**Comment by cicirello** [comment]
@YasiOnFire That is about as convincing as it gets---unlikely two would put a stray apostrophe in the same place. Sorry that I didn't catch that sooner. I'll think about what makes sense for me to do about the other contributor.

For now, I'm reopening your PR, and removing the "duplicate" label.  If you want, you can update from main (it has a few additional translations since your original PR), and then fix the error.  I know it's not the same as if I had simply merged your PR first, but you'd at least be able to get the credit for the PR toward Hacktoberfest for the substantial work that you had done.

**Review by cicirello — APPROVED** [review]

**Comment by YasiOnFire** [comment]
> Sorry that I didn't catch that sooner.

No worries. I didn't mean to sound so salty, but this was just not a cool move from the other contributor.


Thank You for the response @cicirello

**Comment by cicirello** [comment]
@YasiOnFire I definitely agree with you. Not at all cool.

**Pull request merged**
