### PR TITLE
Add Bahasa Indonesia Translation

### LINKED ISSUE #68: Bahasa Indonesia language translation of title template, headings, labels, etc
**Summary**
Add Bahasa Indonesia (id) translations of title template, headings, labels, etc for locale code pt.

### PR DESCRIPTION
**Pull request by berviantoleo**
## Summary

Add Bahasa Indonesia Translation

## Closing Issues

Closes #68 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvements to existing code, such as refactoring or optimizations (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](https://github.com/cicirello/.github/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cicirello** [comment]
@berviantoleo Thank you for contributing. I just merged it into main. Sometime next week I'll create a release that includes this (and a few others that are being worked on).

**Comment by berviantoleo** [comment]
Thank you.

**Comment by cicirello** [comment]
@berviantoleo This just went live with release v1.9.0. :rocket:

**Comment by berviantoleo** [comment]
Thank you.

Cool. I've tried mine too.

https://github.com/berviantoleo/mycapturepicrepo/blob/master/images/userstats.svg

**Pull request merged**
