### PR TITLE
feat: Added Swedish language translation

### PR DESCRIPTION
**Pull request by Viveksati5143**
## Summary

Adding Swedish translations

## Closing Issues

Closes: #94 

## Types of changes

- [X] I have read the [**CONTRIBUTING**](https://github.com/cicirello/.github/blob/main/CONTRIBUTING.md) document.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Improvements to existing code, such as refactoring or optimizations (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by cicirello — APPROVED** [review]

**Comment by cicirello** [comment]
@Viveksati5143 thanks for contributing. I just merged this. One day later this week I'll create a release including this.

**Comment by Viveksati5143** [comment]
> @Viveksati5143 thanks for contributing. I just merged this. One day later this week I'll create a release including this.

Sure @cicirello, will wait!!

**Comment by cicirello** [comment]
@Viveksati5143 I just released v1.21.0 that includes this translation (also available via major tag v1). 🚀 Thank you again for contributing.

**Comment by Viveksati5143** [comment]
> @Viveksati5143 I just released v1.21.0 that includes this translation (also available via major tag v1). 🚀 Thank you again for contributing.

That's great news!!

**Pull request merged**
